--
-- PostgreSQL database dump
--

\restrict RS2m5fYUe5pYZJGPMQTxyPgJ1Ncc4gmlafWps5oXfgli4aybHEVLIAhu4gHPQHh

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

-- Started on 2026-07-02 17:45:18

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 16391)
-- Name: products; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.products (
    id bigint NOT NULL,
    description character varying(255),
    name character varying(100) NOT NULL,
    price numeric(10,2) NOT NULL,
    quantity integer NOT NULL
);


ALTER TABLE public.products OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16390)
-- Name: products_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4960 (class 0 OID 16391)
-- Dependencies: 220
-- Data for Name: products; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.products (id, description, name, price, quantity) FROM stdin;
5	School bag for children	school bag	1000.00	7
6	Nike boots	Shoes	500.00	5
8	Nike boots	Shoes	500.00	5
9	Wireless Bluetooth Headphones	Headphones	200.00	5
10	Flask water bottle	Bottle	50.00	3
\.


--
-- TOC entry 4966 (class 0 OID 0)
-- Dependencies: 219
-- Name: products_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.products_id_seq', 10, true);


--
-- TOC entry 4811 (class 2606 OID 16401)
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


-- Completed on 2026-07-02 17:45:19

--
-- PostgreSQL database dump complete
--

\unrestrict RS2m5fYUe5pYZJGPMQTxyPgJ1Ncc4gmlafWps5oXfgli4aybHEVLIAhu4gHPQHh

